# Site settings
title: Cristian's Portfolio
description: Cristian Morataya portfolio showing skills and projects, also the blog post.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Cristian Morataya
user_description: I'm software developer with emphasis in programming skills, but also database knowledge, testing, design and project configuration. Lately introduced in the game development world, specially in the programming and art area. For development use any open source solution, and my primary OS is GNU/Linux.
user_title: Game Developer / Software Developer
email: cris.morataya@gmail.com
twitter_username: ccmorataya
github_username:  ccmorataya
#gplus_username:  lorem_ipsum

# Build settings
markdown: kramdown
plugins:
    - jekyll-feed
    - jemoji

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
